package com.lottery.agent.dao;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_area", "id", Area.class);
		arp.addMapping("t_currency", "id", Currency.class);
		arp.addMapping("t_game", "id", Game.class);
		arp.addMapping("t_permission", "id", Permission.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_game_rel", "id", UserGameRel.class);
		arp.addMapping("t_user_login_info", "id", UserLoginInfo.class);
		// Composite Primary Key order: permission_id,user_id
		arp.addMapping("t_user_permission", "permission_id,user_id", UserPermission.class);
	}
}

