package com.lottery.agent.dao;

import com.lottery.agent.entity.BaseCurrency;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Currency extends BaseCurrency<Currency> {
	public static final Currency dao = new Currency().dao();

	public List<Currency> getAllCurrency() {
		return find("select id, currency_code, currency_name, exchange_rate, is_default from t_currency order by id");
	}

	public Currency getCurrency(int id) {
		return findById(id);
	}

	public Currency getCurrency(String code) {
		return findFirst("select id, currency_code, currency_name, exchange_rate, is_default from t_currency where currency_code = ?", code);
	}
}
