package com.lottery.agent.dao;

import com.lottery.agent.entity.BaseGame;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game().dao();

	public List<Game> getGameList() {
		String sql = "select *, 0 as relate_id from t_game order by id";
		return find(sql);
	}
}
