package com.lottery.agent.dao;

import com.lottery.agent.entity.BaseUserPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPermission extends BaseUserPermission<UserPermission> {
	public static final UserPermission dao = new UserPermission().dao();
}
