package com.lottery.agent.dao;

import com.jfinal.kit.LogKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.lottery.agent.entity.BaseUserGameRel;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGameRel extends BaseUserGameRel<UserGameRel> {
	public static final UserGameRel dao = new UserGameRel().dao();

	public List<Record> getUserGameList(int userId) {
		String sql = "select g.*, ug.id as relate_id from t_game g, t_user_game_rel ug where g.id = ug.game_id and ug.user_id = ?";
		return Db.find(sql, userId);
	}

	public boolean saveUserGame(UserGameRel userGameRel) {
		boolean result = false;

		try {
			if (userGameRel.getId() != null && userGameRel.getId() > 0) {
				result = userGameRel.update();
			} else {
				if (userGameRel.getAllComission() == null) userGameRel.setAllComission(0);
				if (userGameRel.getComission() == null) userGameRel.setComission(0);
				userGameRel.setId(null);
				result = userGameRel.save();
			}
		} catch (Exception e) {
			LogKit.error(e.getMessage(), e);
		}
		return result;
	}

	public boolean removeUserGame(int relateId) {
		return deleteById(relateId);
	}
}
