package com.lottery.agent.dao;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.lottery.agent.common.Consts;
import com.lottery.agent.entity.BaseUserLoginInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoginInfo extends BaseUserLoginInfo<UserLoginInfo> {
	public static final UserLoginInfo dao = new UserLoginInfo().dao();

	public UserLoginInfo getLoginInfo(Integer userId) {
		if (userId == null) return null;

		String sql = "select * from t_user_login_info where user_id = ? and status = ?";
		return findFirst(sql, userId, Consts.STATUS_YES);
	}
	public UserLoginInfo getLoginInfo(String token) {
		if (StrKit.isBlank(token)) return null;

		String sql = "select * from t_user_login_info where token = ? and status = ?";
		return findFirst(sql, token, Consts.STATUS_YES);
	}

	public void UserAbort(Integer userId) {
		if (userId != null) {
			String sql = "update t_user_login_info set status = ?, logout_time = now() " +
					"where user_id = ? and status = 1";
			Db.update(sql, Consts.ACCOUNT_ABORT, userId);
		}
	}
}
