package com.lottery.agent.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCurrencyCode(java.lang.String currencyCode) {
		set("currency_code", currencyCode);
		return (M)this;
	}
	
	public java.lang.String getCurrencyCode() {
		return getStr("currency_code");
	}

	public M setFirstName(java.lang.String firstName) {
		set("first_name", firstName);
		return (M)this;
	}
	
	public java.lang.String getFirstName() {
		return getStr("first_name");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setVerificationCode(java.lang.String verificationCode) {
		set("verification_code", verificationCode);
		return (M)this;
	}
	
	public java.lang.String getVerificationCode() {
		return getStr("verification_code");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setUserType(java.lang.Integer userType) {
		set("user_type", userType);
		return (M)this;
	}
	
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public M setUserLevel(java.lang.Integer userLevel) {
		set("user_level", userLevel);
		return (M)this;
	}
	
	public java.lang.Integer getUserLevel() {
		return getInt("user_level");
	}

	public M setIsPause(java.lang.Integer isPause) {
		set("is_pause", isPause);
		return (M)this;
	}
	
	public java.lang.Integer getIsPause() {
		return getInt("is_pause");
	}

	public M setCanBet(java.lang.Integer canBet) {
		set("can_bet", canBet);
		return (M)this;
	}
	
	public java.lang.Integer getCanBet() {
		return getInt("can_bet");
	}

	public M setComission(java.lang.Integer comission) {
		set("comission", comission);
		return (M)this;
	}
	
	public java.lang.Integer getComission() {
		return getInt("comission");
	}

	public M setPauseUser(java.lang.Integer pauseUser) {
		set("pause_user", pauseUser);
		return (M)this;
	}
	
	public java.lang.Integer getPauseUser() {
		return getInt("pause_user");
	}

	public M setStakedUser(java.lang.Integer stakedUser) {
		set("staked_user", stakedUser);
		return (M)this;
	}
	
	public java.lang.Integer getStakedUser() {
		return getInt("staked_user");
	}

	public M setMaxLevel(java.lang.Integer maxLevel) {
		set("max_level", maxLevel);
		return (M)this;
	}
	
	public java.lang.Integer getMaxLevel() {
		return getInt("max_level");
	}

	public M setIsAnonymous(java.lang.Integer isAnonymous) {
		set("is_anonymous", isAnonymous);
		return (M)this;
	}
	
	public java.lang.Integer getIsAnonymous() {
		return getInt("is_anonymous");
	}

	public M setSubAccount(java.lang.Integer subAccount) {
		set("sub_account", subAccount);
		return (M)this;
	}
	
	public java.lang.Integer getSubAccount() {
		return getInt("sub_account");
	}

	public M setSubType(java.lang.Integer subType) {
		set("sub_type", subType);
		return (M)this;
	}
	
	public java.lang.Integer getSubType() {
		return getInt("sub_type");
	}

	public M setMasterId(java.lang.Integer masterId) {
		set("master_id", masterId);
		return (M)this;
	}
	
	public java.lang.Integer getMasterId() {
		return getInt("master_id");
	}

	public M setNextTime(java.lang.Integer nextTime) {
		set("next_time", nextTime);
		return (M)this;
	}
	
	public java.lang.Integer getNextTime() {
		return getInt("next_time");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setWechat(java.lang.String wechat) {
		set("wechat", wechat);
		return (M)this;
	}
	
	public java.lang.String getWechat() {
		return getStr("wechat");
	}

	public M setMaxWin(java.math.BigDecimal maxWin) {
		set("max_win", maxWin);
		return (M)this;
	}
	
	public java.math.BigDecimal getMaxWin() {
		return get("max_win");
	}

	public M setMaxLose(java.math.BigDecimal maxLose) {
		set("max_lose", maxLose);
		return (M)this;
	}
	
	public java.math.BigDecimal getMaxLose() {
		return get("max_lose");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.lang.Integer updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateTime() {
		return getInt("update_time");
	}

}
