package com.lottery.agent.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGame<M extends BaseGame<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGameName(java.lang.String gameName) {
		set("game_name", gameName);
		return (M)this;
	}
	
	public java.lang.String getGameName() {
		return getStr("game_name");
	}

	public M setOdds(java.lang.Integer odds) {
		set("odds", odds);
		return (M)this;
	}
	
	public java.lang.Integer getOdds() {
		return getInt("odds");
	}

	public M setWebsite(java.lang.String website) {
		set("website", website);
		return (M)this;
	}
	
	public java.lang.String getWebsite() {
		return getStr("website");
	}

}
